//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TBOffice.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspApplication
    {
        public AspApplication()
        {
            this.AspMemberships = new HashSet<AspMembership>();
            this.AspRoles = new HashSet<AspRole>();
            this.AspUsers = new HashSet<AspUser>();
        }
    
        public string ApplicationName { get; set; }
        public System.Guid ApplicationId { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<AspMembership> AspMemberships { get; set; }
        public virtual ICollection<AspRole> AspRoles { get; set; }
        public virtual ICollection<AspUser> AspUsers { get; set; }
    }
}
