//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TBOffice.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendanceCount
    {
        public int ServiceAttendanceID { get; set; }
        public Nullable<int> SundayID { get; set; }
        public Nullable<int> ServiceID { get; set; }
        public Nullable<short> HeadCount { get; set; }
        public Nullable<short> CardCount { get; set; }
        public Nullable<double> CardPct { get; set; }
        public Nullable<short> AdultSSCount { get; set; }
        public Nullable<short> ChildSSCount { get; set; }
        public Nullable<short> YouthSSCount { get; set; }
        public Nullable<short> ParkingCount { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    
        public virtual Service Service { get; set; }
        public virtual Sunday Sunday { get; set; }
    }
}
