//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TBOffice.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Congregation
    {
        public Congregation()
        {
            this.Services = new HashSet<Service>();
        }
    
        public int CongregationID { get; set; }
        public string CongregationDesc { get; set; }
    
        public virtual ICollection<Service> Services { get; set; }
    }
}
