//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TBOffice.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EECategory
    {
        public EECategory()
        {
            this.TBUsers = new HashSet<TBUser>();
        }
    
        public int EECategoryID { get; set; }
        public string ShortDesc { get; set; }
    
        public virtual ICollection<TBUser> TBUsers { get; set; }
    }
}
