//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TBOffice.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EECompensation
    {
        public int CompID { get; set; }
        public int CompUserID { get; set; }
        public int FiscalYear { get; set; }
        public bool IsExempt { get; set; }
        public decimal Salary { get; set; }
        public decimal Housing { get; set; }
        public decimal HourlyRate { get; set; }
        public byte VacationAllotment { get; set; }
        public byte IllnessAllotment { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual TBUser TBUser { get; set; }
        public virtual t_acct_fiscal_year t_acct_fiscal_year { get; set; }
    }
}
