//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TBOffice.Model
{
    using System;
    
    public partial class fxMenu
    {
        public int MenuID { get; set; }
        public Nullable<int> ParentMenuID { get; set; }
        public string ShortDesc { get; set; }
        public string NavigateUrl { get; set; }
        public string ImageUrl { get; set; }
        public string Target { get; set; }
        public bool Enabled { get; set; }
    }
}
