//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TBOffice.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public Service()
        {
            this.Offerings = new HashSet<Offering>();
            this.AttendanceCounts = new HashSet<AttendanceCount>();
        }
    
        public int ServiceID { get; set; }
        public Nullable<int> CongregationID { get; set; }
        public string ServiceCode { get; set; }
    
        public virtual Congregation Congregation { get; set; }
        public virtual ICollection<Offering> Offerings { get; set; }
        public virtual ICollection<AttendanceCount> AttendanceCounts { get; set; }
    }
}
