//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TBOffice.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_acct_trans_txfr
    {
        public long TransId { get; set; }
        public long EntryKey { get; set; }
        public string Vendor { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public string Memo { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string DebitAccount { get; set; }
        public string CreditAccount { get; set; }
        public Nullable<int> TransType { get; set; }
        public Nullable<int> CheckNum { get; set; }
        public Nullable<bool> IsChanged { get; set; }
        public Nullable<bool> IsNew { get; set; }
        public Nullable<System.DateTime> CDT { get; set; }
    
        public virtual t_acct_trans t_acct_trans { get; set; }
    }
}
