//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TBOffice.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_acct_budget
    {
        public long BudgetItemId { get; set; }
        public long FiscalYear { get; set; }
        public int AcctId { get; set; }
        public Nullable<decimal> BudgetAmt { get; set; }
        public Nullable<decimal> M1Amt { get; set; }
        public Nullable<decimal> M2Amt { get; set; }
        public Nullable<decimal> M3Amt { get; set; }
        public Nullable<decimal> M4Amt { get; set; }
        public Nullable<decimal> M5Amt { get; set; }
        public Nullable<decimal> M6Amt { get; set; }
        public Nullable<decimal> M7Amt { get; set; }
        public Nullable<decimal> M8Amt { get; set; }
        public Nullable<decimal> M9Amt { get; set; }
        public Nullable<decimal> M10Amt { get; set; }
        public Nullable<decimal> M11Amt { get; set; }
        public Nullable<decimal> M12Amt { get; set; }
        public Nullable<int> CB { get; set; }
        public Nullable<System.DateTime> CDT { get; set; }
        public Nullable<int> MB { get; set; }
        public Nullable<System.DateTime> MDT { get; set; }
    
        public virtual t_acct t_acct { get; set; }
    }
}
