//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TBOffice.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_acct_fiscal_year
    {
        public t_acct_fiscal_year()
        {
            this.t_acct_beg_bal = new HashSet<t_acct_beg_bal>();
            this.tblEECompensations = new HashSet<EECompensation>();
        }
    
        public int FiscalYear { get; set; }
        public Nullable<int> EndYear { get; set; }
        public string ShortDesc { get; set; }
        public Nullable<System.DateTime> BegDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    
        public virtual ICollection<t_acct_beg_bal> t_acct_beg_bal { get; set; }
        public virtual ICollection<EECompensation> tblEECompensations { get; set; }
    }
}
