//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TBOffice.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_acct_fund
    {
        public t_acct_fund()
        {
            this.t_acct = new HashSet<t_acct>();
        }
    
        public byte FundId { get; set; }
        public string ShortDesc { get; set; }
        public Nullable<bool> IsSchoolFund { get; set; }
        public Nullable<byte> SeqNum { get; set; }
    
        public virtual ICollection<t_acct> t_acct { get; set; }
    }
}
