//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TBOffice.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_acct_trans_type
    {
        public t_acct_trans_type()
        {
            this.t_acct_trans = new HashSet<t_acct_trans>();
        }
    
        public byte TransTypeId { get; set; }
        public string ShortDesc { get; set; }
    
        public virtual ICollection<t_acct_trans> t_acct_trans { get; set; }
    }
}
