//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TBOffice.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_acct_trans
    {
        public long TransId { get; set; }
        public Nullable<long> EntryKey { get; set; }
        public System.DateTime TransDate { get; set; }
        public decimal TransAmt { get; set; }
        public byte TransTypeId { get; set; }
        public int CreditAcctId { get; set; }
        public int DebitAcctId { get; set; }
        public Nullable<int> CheckNum { get; set; }
        public string Memo { get; set; }
        public string Vendor { get; set; }
        public Nullable<int> CB { get; set; }
        public Nullable<System.DateTime> CDT { get; set; }
        public Nullable<int> MB { get; set; }
        public Nullable<System.DateTime> MDT { get; set; }
    
        public virtual t_acct t_acct { get; set; }
        public virtual t_acct t_acct1 { get; set; }
        public virtual t_acct_trans_txfr t_acct_trans_txfr { get; set; }
        public virtual t_acct_trans_type t_acct_trans_type { get; set; }
    }
}
