//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TBOffice.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_acct_fiscal_month
    {
        public int MonthId { get; set; }
        public string ShortDesc { get; set; }
        public Nullable<System.DateTime> MonthBeg { get; set; }
        public Nullable<System.DateTime> MonthEnd { get; set; }
        public Nullable<long> FiscalYear { get; set; }
        public Nullable<int> MonthNum { get; set; }
    }
}
