//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TBOffice.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_sec_user
    {
        public t_sec_user()
        {
            this.t_sec_user_role = new HashSet<t_sec_user_role>();
        }
    
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public Nullable<byte> IsEnabled { get; set; }
        public Nullable<byte> CongregationTypeId { get; set; }
    
        public virtual ICollection<t_sec_user_role> t_sec_user_role { get; set; }
    }
}
