//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TBOffice.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_sec_user_role
    {
        public int UserId { get; set; }
        public int RoleTypeId { get; set; }
        public Nullable<byte> IsEnabled { get; set; }
    
        public virtual t_sec_role_type t_sec_role_type { get; set; }
        public virtual t_sec_user t_sec_user { get; set; }
    }
}
