//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TBOffice.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TORequest
    {
        public int TORequestID { get; set; }
        public System.DateTime TODate { get; set; }
        public int TOUserID { get; set; }
        public System.DateTime RequestDT { get; set; }
        public Nullable<System.DateTime> ApprovalDT { get; set; }
        public Nullable<int> ApprovalUserID { get; set; }
        public string Comment { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual TBUser TORequestUser { get; set; }
        public virtual TBUser ApprovalUser { get; set; }
    }
}
