//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TBOffice.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSEntry
    {
        public int TSEntryID { get; set; }
        public int UserID { get; set; }
        public System.DateTime TSDate { get; set; }
        public decimal WorkHours { get; set; }
        public decimal VacationHours { get; set; }
        public decimal SickHours { get; set; }
        public decimal HolidayHours { get; set; }
        public Nullable<decimal> TotalHours { get; set; }
        public bool IsAdjustment { get; set; }
        public byte[] RowVersion { get; set; }
        public string Notes { get; set; }
        public Nullable<int> PayPeriodId { get; set; }
    
        public virtual TBUser TBUser { get; set; }
    }
}
