//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TBOffice.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSWeek
    {
        public int TSWeekID { get; set; }
        public int UserID { get; set; }
        public int WeekID { get; set; }
        public Nullable<decimal> WorkHours { get; set; }
        public decimal VacationHours { get; set; }
        public decimal SickHours { get; set; }
        public decimal HolidayHours { get; set; }
        public Nullable<decimal> TotalHours { get; set; }
        public decimal BalanceHours { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual TBUser TBUser { get; set; }
        public virtual Week Week { get; set; }
    }
}
