//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TBOffice.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_GF_IncomeDept_Budget_By_FY
    {
        public int deptacctid { get; set; }
        public string DeptDesc { get; set; }
        public int AcctId { get; set; }
        public string acctdesc { get; set; }
        public Nullable<decimal> BudgetAmt { get; set; }
        public Nullable<long> FiscalYear { get; set; }
    }
}
