//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TBOffice.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwBudgetMaster
    {
        public int AcctId { get; set; }
        public byte AcctTypeId { get; set; }
        public Nullable<decimal> BegBalAmt { get; set; }
        public Nullable<int> DeptAcctId { get; set; }
        public Nullable<byte> FundId { get; set; }
        public Nullable<int> SubDeptAcctId { get; set; }
        public string AcctDesc { get; set; }
        public Nullable<long> BudgetItemId { get; set; }
        public Nullable<long> FiscalYear { get; set; }
        public Nullable<int> BudgetAcctId { get; set; }
        public decimal BudgetAmt { get; set; }
        public decimal M1Amt { get; set; }
        public decimal M2Amt { get; set; }
        public decimal M3Amt { get; set; }
        public decimal M4Amt { get; set; }
        public decimal M5Amt { get; set; }
        public decimal M6Amt { get; set; }
        public decimal M7Amt { get; set; }
        public decimal M8Amt { get; set; }
        public decimal M9Amt { get; set; }
        public decimal M10Amt { get; set; }
        public decimal M11Amt { get; set; }
        public decimal M12Amt { get; set; }
        public Nullable<int> CB { get; set; }
        public Nullable<System.DateTime> CDT { get; set; }
        public Nullable<int> MB { get; set; }
        public Nullable<System.DateTime> MDT { get; set; }
    }
}
