//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TBOffice.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwExpenseDept
    {
        public int AcctId { get; set; }
        public string ShortDesc { get; set; }
        public byte AcctTypeId { get; set; }
        public Nullable<byte> FundId { get; set; }
        public Nullable<int> DeptAcctId { get; set; }
        public Nullable<int> SubDeptAcctId { get; set; }
        public Nullable<decimal> BegBalAmt { get; set; }
        public Nullable<int> CB { get; set; }
        public Nullable<System.DateTime> CDT { get; set; }
        public Nullable<int> MB { get; set; }
        public Nullable<System.DateTime> MDT { get; set; }
    }
}
