//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TBOffice.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwTransMaster
    {
        public long TransId { get; set; }
        public System.DateTime TransDate { get; set; }
        public Nullable<decimal> TransAmt { get; set; }
        public string Memo { get; set; }
        public string Vendor { get; set; }
        public Nullable<byte> FundId { get; set; }
        public int AcctId { get; set; }
        public byte AcctTypeId { get; set; }
        public Nullable<int> DeptAcctId { get; set; }
        public Nullable<int> SubDeptAcctId { get; set; }
        public string AcctDesc { get; set; }
    }
}
