//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TBOffice.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Week
    {
        public Week()
        {
            this.TSWeeks = new HashSet<TSWeek>();
        }
    
        public int WeekID { get; set; }
        public byte WeekNum { get; set; }
        public int YearNum { get; set; }
        public System.DateTime BegDate { get; set; }
        public System.DateTime EndDate { get; set; }
    
        public virtual ICollection<TSWeek> TSWeeks { get; set; }
    }
}
