//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TBOffice.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class YearType
    {
        public string Id { get; set; }
        public string ShortDesc { get; set; }
        public Nullable<System.DateTime> StartDt { get; set; }
        public Nullable<System.DateTime> EndDt { get; set; }
        public Nullable<bool> IsSummer { get; set; }
    }
}
